import os
from google.genai import types


schema_write_file = types.FunctionDeclaration(
    name="write_file",
    description="write or overwrite to a file",
    parameters=types.Schema(
        type=types.Type.OBJECT,
        properties={
            "file_path": types.Schema(
                type=types.Type.STRING,
                description="file_path, relative to the working directory(default is working directory itself"
            ),
            "content":types.Schema(
                type=types.Type.STRING,
                description="content, the actual text generated by ai agent to be writted into file at file_path"
            ),
        }
    )
)


def write_file(working_directory: str, file_path: str, content: str) -> str:
    abs_path = os.path.abspath(working_directory)
    target_path = os.path.normpath(os.path.join(abs_path, file_path))
    valid_target_path = os.path.commonpath([abs_path, target_path]) == abs_path 
    
    if not valid_target_path:
        return f'Error: Cannot write to "{file_path}" as it is outside the permitted working directory'
    
    if os.path.isdir(target_path):
        return f'Error: Cannot write to "{file_path}" as it is a directory'
    # create any missing parent directory of file_path
    os.makedirs(os.path.dirname(target_path), exist_ok=True)

    try:
        with open(target_path, "w") as f:
            f.write(content)
            return f'Successfully wrote to "{file_path}" ({len(content)} characters written)'
    except Exception as e:
        return f"Error: unable to complete writing: {e}"
